# This workflow will build an image of a service and export it to the github workspace

name: Deploy the image to k8s

on:
  workflow_call:
    inputs:
      infra_repo: 
        required: true
        type: string
      image:
        required: true
        type: string 
      dh_registry:
        required: true
        type: string
      dh_repository:
        required: true
        type: string
      deploy_file:
        required: true
        type: string
    secrets:
      git_token:
        required: true
      

jobs:
  deploy-to-k8s:
    name: Trigger deploy to k8s cluster
    runs-on: ubuntu-latest

    steps:
              
      - name: Checkout CD action
        uses: actions/checkout@v3
        with:
          ref: 'main'
          repository: ${{ inputs.infra_repo }}
          token: ${{ secrets.git_token }}
    
      - name: Replace image in the deployment file
        env:
          IMAGE_TAG: ${{ inputs.image }}
          DH_REPOSITORY: ${{ inputs.dockerhub_repository }}
          DEPLOY_FILE: ${{ inputs.deploy_file }}
        run: |
            sed -i 's/${{env.DH_REPOSITORY}}.*/${{env.DH_REPOSITORY}}:${{env.IMAGE_TAG}}/g' ${{ env.DEPLOY_FILE }}
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Automatic push from git Actions for ${{github.workflow}}"
            git push
