# This workflow will build an image of a service and export it to the github workspace

name: Deploy the image to k8s

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      infra_repo: 
        required: true
        type: string
      image:
        required: true
        type: string 
    secrets:
      git_token:
        required: true
      dockerhub_registry:
        required: true
      dockerhub_repository:
        required: true
      deploy_app_name:
        required: true
      

jobs:
  deploy-to-k8s:
    name: Trigger deploy to k8s cluster
    runs-on: ubuntu-latest

    steps:
    
      - name: Map environment variables
        uses: kanga333/variable-mapper@master
        with:
          key: "${{ inputs.target }}"
          map: |
            {
              "preprod": { "environment": "RC" },
              "develop": { "environment": "QA" }
            }
            
      - name: Checkout CD action
        uses: actions/checkout@v3
        with:
          ref: 'main'
          repository: ${{ inputs.infra_repo }}
          token: ${{ secrets.git_token }}
    
      - name: Replace image in the deployment file
        env:
          ENVIRONNEMENT: ${{ inputs.target == 'develop' && 'QA' || 'RC' }}
          IMAGE_TAG: ${{ inputs.image }}
          DH_REPOSITORY: ${{ secrets.dockerhub_repository }}
          SVC_NAME: ${{ secrets.deploy_app_name }}
        run: |
            sed -i 's/${{env.DH_REPOSITORY}}.*/${{env.DH_REPOSITORY}}:${{env.IMAGE_TAG}}/g' B2C/${{env.ENVIRONNEMENT}}/MS/${{env.SVC_NAME}}/${{env.SVC_NAME}}-deployment.yaml
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Automatic push from git Actions for ${{github.workflow}}"
            git push
