# This workflow will get the last image deployed on the preprod environment and
# trigger a deploy to the production environment

name: Deploy an image to prod repository

on:
  workflow_call:
    inputs:
      tag: 
        required: true
        type: string
      dh_registry:
        type: string
        required: true
      dh_preprod_repository:
        type: string
        required: true
      dh_prod_repository:
        type: string
        required: true
    secrets:
      dh_username:
        required: true
      dh_token:
        required: true

jobs:
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.dh_username }}
          password: ${{ secrets.dh_token }}
    
      - name: Move image from Preprod to Prod in DockerHub
        env:
          dh_registry: ${{ inputs.dh_registry }}
          dh_preprod_repository: ${{ inputs.dh_preprod_repository }}
          dh_prod_repository: ${{ inputs.dh_prod_repository }}
          image: ${{ inputs.tag }}
        run: |
          echo "Pull image from DockerHub..."
          docker pull gekkogroup/$dh_preprod_repository:$image
          echo "Tag new prod image"
          docker tag gekkogroup/$dh_preprod_repository:$image $dh_registry/$dh_prod_repository:$image
          echo "Push image to prod repository"
          docker push gekkogroup/$dh_prod_repository:$image
